spring.application.name=spring-postgres-crud

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#use a legit Gmail account to test endpoints, that's how SMTP works
spring.mail.username=example-name@gmail.com
spring.mail.password=fmbmmaweevwabioh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
